language: haskell # there wasn't C so I chose something cool
before_install:
  - wget http://www.atmel.com/Images/avr-headers.zip
  - wget http://www.atmel.com/Images/avr32-gnu-toolchain-3.4.0.332-linux.any.x86.tar.gz
install:
  - tar -xzf avr32-gnu-toolchain-3.4.0.332-linux.any.x86.tar.gz
  - mv avr32-gnu-toolchain-linux_x86 avr32-tools
  - unzip -qq avr-headers.zip && mv avr-headers/avr32 avr32-tools/avr32/include
  - export PATH=$PWD/avr32-tools/bin:$PATH
before_script:
  - avr32-gcc --version

script:
  - make
  - cp examples/adc.cpp main.cpp && make re
  - cp examples/rtc_interrupt.cpp main.c && make re
  - cp examples/spi.cpp main.cpp && make re
  - cp examples/toggle_led.cpp main.cpp && make re
  - cp examples/displays/hd44780.cpp main.cpp && make re
  - make cleanall

branches:
  only:
    - master

notifications:
  email: false
